# TCL File Generated by Component Editor 15.0
# Sun Apr 15 23:08:56 CDT 2018
# DO NOT MODIFY


# 
# mouse_core "mouse_core" v1.1
#  2018.04.15.23:08:56
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module mouse_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME mouse_core
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ece385
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mouse_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_mouse_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_mouse_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_mouse_interface
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point Mouse_Slave
# 
add_interface Mouse_Slave avalon end
set_interface_property Mouse_Slave addressUnits WORDS
set_interface_property Mouse_Slave associatedClock CLK
set_interface_property Mouse_Slave associatedReset RESET
set_interface_property Mouse_Slave bitsPerSymbol 8
set_interface_property Mouse_Slave burstOnBurstBoundariesOnly false
set_interface_property Mouse_Slave burstcountUnits WORDS
set_interface_property Mouse_Slave explicitAddressSpan 0
set_interface_property Mouse_Slave holdTime 0
set_interface_property Mouse_Slave linewrapBursts false
set_interface_property Mouse_Slave maximumPendingReadTransactions 0
set_interface_property Mouse_Slave maximumPendingWriteTransactions 0
set_interface_property Mouse_Slave readLatency 0
set_interface_property Mouse_Slave readWaitStates 0
set_interface_property Mouse_Slave readWaitTime 0
set_interface_property Mouse_Slave setupTime 0
set_interface_property Mouse_Slave timingUnits Cycles
set_interface_property Mouse_Slave writeWaitTime 0
set_interface_property Mouse_Slave ENABLED true
set_interface_property Mouse_Slave EXPORT_OF ""
set_interface_property Mouse_Slave PORT_NAME_MAP ""
set_interface_property Mouse_Slave CMSIS_SVD_VARIABLES ""
set_interface_property Mouse_Slave SVD_ADDRESS_GROUP ""

add_interface_port Mouse_Slave AVL_CS chipselect Input 1
add_interface_port Mouse_Slave AVL_BYTE_EN byteenable Input 4
add_interface_port Mouse_Slave AVL_ADDR address Input 4
add_interface_port Mouse_Slave AVL_READDATA readdata Output 32
add_interface_port Mouse_Slave AVL_WRITEDATA writedata Input 32
add_interface_port Mouse_Slave AVL_WRITE write Input 1
add_interface_port Mouse_Slave AVL_READ read Input 1
set_interface_assignment Mouse_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment Mouse_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Mouse_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Mouse_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point EXPORT_DATA
# 
add_interface EXPORT_DATA conduit end
set_interface_property EXPORT_DATA associatedClock CLK
set_interface_property EXPORT_DATA associatedReset ""
set_interface_property EXPORT_DATA ENABLED true
set_interface_property EXPORT_DATA EXPORT_OF ""
set_interface_property EXPORT_DATA PORT_NAME_MAP ""
set_interface_property EXPORT_DATA CMSIS_SVD_VARIABLES ""
set_interface_property EXPORT_DATA SVD_ADDRESS_GROUP ""

add_interface_port EXPORT_DATA EXPORT_DATA read Output 32

