# TCL File Generated by Component Editor 15.0
# Sun Apr 15 23:04:06 CDT 2018
# DO NOT MODIFY


# 
# mouse_core_remake "mcr" v1.0
#  2018.04.15.23:04:06
# a
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module mouse_core_remake
# 
set_module_property DESCRIPTION a
set_module_property NAME mouse_core_remake
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ece385
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mcr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_mouse_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_mouse_interface.sv SYSTEM_VERILOG PATH avalon_mouse_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point MOUSE_SLAVE
# 
add_interface MOUSE_SLAVE avalon end
set_interface_property MOUSE_SLAVE addressUnits WORDS
set_interface_property MOUSE_SLAVE associatedClock CLK
set_interface_property MOUSE_SLAVE associatedReset RESET
set_interface_property MOUSE_SLAVE bitsPerSymbol 8
set_interface_property MOUSE_SLAVE burstOnBurstBoundariesOnly false
set_interface_property MOUSE_SLAVE burstcountUnits WORDS
set_interface_property MOUSE_SLAVE explicitAddressSpan 0
set_interface_property MOUSE_SLAVE holdTime 0
set_interface_property MOUSE_SLAVE linewrapBursts false
set_interface_property MOUSE_SLAVE maximumPendingReadTransactions 0
set_interface_property MOUSE_SLAVE maximumPendingWriteTransactions 0
set_interface_property MOUSE_SLAVE readLatency 0
set_interface_property MOUSE_SLAVE readWaitStates 0
set_interface_property MOUSE_SLAVE readWaitTime 0
set_interface_property MOUSE_SLAVE setupTime 0
set_interface_property MOUSE_SLAVE timingUnits Cycles
set_interface_property MOUSE_SLAVE writeWaitTime 0
set_interface_property MOUSE_SLAVE ENABLED true
set_interface_property MOUSE_SLAVE EXPORT_OF ""
set_interface_property MOUSE_SLAVE PORT_NAME_MAP ""
set_interface_property MOUSE_SLAVE CMSIS_SVD_VARIABLES ""
set_interface_property MOUSE_SLAVE SVD_ADDRESS_GROUP ""

add_interface_port MOUSE_SLAVE AVL_ADDR address Input 4
add_interface_port MOUSE_SLAVE AVL_CS chipselect Input 1
add_interface_port MOUSE_SLAVE AVL_BYTE_EN byteenable Input 4
add_interface_port MOUSE_SLAVE AVL_READ read Input 1
add_interface_port MOUSE_SLAVE AVL_READDATA readdata Output 32
add_interface_port MOUSE_SLAVE AVL_WRITE write Input 1
add_interface_port MOUSE_SLAVE AVL_WRITEDATA writedata Input 32
set_interface_assignment MOUSE_SLAVE embeddedsw.configuration.isFlash 0
set_interface_assignment MOUSE_SLAVE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment MOUSE_SLAVE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment MOUSE_SLAVE embeddedsw.configuration.isPrintableDevice 0


# 
# connection point EXPORT_DATA
# 
add_interface EXPORT_DATA conduit end
set_interface_property EXPORT_DATA associatedClock CLK
set_interface_property EXPORT_DATA associatedReset RESET
set_interface_property EXPORT_DATA ENABLED true
set_interface_property EXPORT_DATA EXPORT_OF ""
set_interface_property EXPORT_DATA PORT_NAME_MAP ""
set_interface_property EXPORT_DATA CMSIS_SVD_VARIABLES ""
set_interface_property EXPORT_DATA SVD_ADDRESS_GROUP ""

add_interface_port EXPORT_DATA EXPORT_DATA EXPORT_DATA Output 32


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1

