// DE2_115_SOPC_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module DE2_115_SOPC_mm_interconnect_1 (
		input  wire        pll_c2_clk,                                             //                                           pll_c2.clk
		input  wire        clock_crossing_io_m0_reset_reset_bridge_in_reset_reset, // clock_crossing_io_m0_reset_reset_bridge_in_reset.reset
		input  wire [21:0] clock_crossing_io_m0_address,                           //                             clock_crossing_io_m0.address
		output wire        clock_crossing_io_m0_waitrequest,                       //                                                 .waitrequest
		input  wire [0:0]  clock_crossing_io_m0_burstcount,                        //                                                 .burstcount
		input  wire [3:0]  clock_crossing_io_m0_byteenable,                        //                                                 .byteenable
		input  wire        clock_crossing_io_m0_read,                              //                                                 .read
		output wire [31:0] clock_crossing_io_m0_readdata,                          //                                                 .readdata
		output wire        clock_crossing_io_m0_readdatavalid,                     //                                                 .readdatavalid
		input  wire        clock_crossing_io_m0_write,                             //                                                 .write
		input  wire [31:0] clock_crossing_io_m0_writedata,                         //                                                 .writedata
		input  wire        clock_crossing_io_m0_debugaccess,                       //                                                 .debugaccess
		output wire [1:0]  CY7C67200_IF_0_hpi_address,                             //                               CY7C67200_IF_0_hpi.address
		output wire        CY7C67200_IF_0_hpi_write,                               //                                                 .write
		output wire        CY7C67200_IF_0_hpi_read,                                //                                                 .read
		input  wire [31:0] CY7C67200_IF_0_hpi_readdata,                            //                                                 .readdata
		output wire [31:0] CY7C67200_IF_0_hpi_writedata,                           //                                                 .writedata
		output wire        CY7C67200_IF_0_hpi_chipselect,                          //                                                 .chipselect
		output wire [0:0]  sysid_control_slave_address,                            //                              sysid_control_slave.address
		input  wire [31:0] sysid_control_slave_readdata                            //                                                 .readdata
	);

	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_waitrequest;   // clock_crossing_io_m0_agent:av_waitrequest -> clock_crossing_io_m0_translator:uav_waitrequest
	wire  [31:0] clock_crossing_io_m0_translator_avalon_universal_master_0_readdata;      // clock_crossing_io_m0_agent:av_readdata -> clock_crossing_io_m0_translator:uav_readdata
	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_debugaccess;   // clock_crossing_io_m0_translator:uav_debugaccess -> clock_crossing_io_m0_agent:av_debugaccess
	wire  [21:0] clock_crossing_io_m0_translator_avalon_universal_master_0_address;       // clock_crossing_io_m0_translator:uav_address -> clock_crossing_io_m0_agent:av_address
	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_read;          // clock_crossing_io_m0_translator:uav_read -> clock_crossing_io_m0_agent:av_read
	wire   [3:0] clock_crossing_io_m0_translator_avalon_universal_master_0_byteenable;    // clock_crossing_io_m0_translator:uav_byteenable -> clock_crossing_io_m0_agent:av_byteenable
	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_readdatavalid; // clock_crossing_io_m0_agent:av_readdatavalid -> clock_crossing_io_m0_translator:uav_readdatavalid
	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_lock;          // clock_crossing_io_m0_translator:uav_lock -> clock_crossing_io_m0_agent:av_lock
	wire         clock_crossing_io_m0_translator_avalon_universal_master_0_write;         // clock_crossing_io_m0_translator:uav_write -> clock_crossing_io_m0_agent:av_write
	wire  [31:0] clock_crossing_io_m0_translator_avalon_universal_master_0_writedata;     // clock_crossing_io_m0_translator:uav_writedata -> clock_crossing_io_m0_agent:av_writedata
	wire   [2:0] clock_crossing_io_m0_translator_avalon_universal_master_0_burstcount;    // clock_crossing_io_m0_translator:uav_burstcount -> clock_crossing_io_m0_agent:av_burstcount
	wire  [31:0] sysid_control_slave_agent_m0_readdata;                                   // sysid_control_slave_translator:uav_readdata -> sysid_control_slave_agent:m0_readdata
	wire         sysid_control_slave_agent_m0_waitrequest;                                // sysid_control_slave_translator:uav_waitrequest -> sysid_control_slave_agent:m0_waitrequest
	wire         sysid_control_slave_agent_m0_debugaccess;                                // sysid_control_slave_agent:m0_debugaccess -> sysid_control_slave_translator:uav_debugaccess
	wire  [21:0] sysid_control_slave_agent_m0_address;                                    // sysid_control_slave_agent:m0_address -> sysid_control_slave_translator:uav_address
	wire   [3:0] sysid_control_slave_agent_m0_byteenable;                                 // sysid_control_slave_agent:m0_byteenable -> sysid_control_slave_translator:uav_byteenable
	wire         sysid_control_slave_agent_m0_read;                                       // sysid_control_slave_agent:m0_read -> sysid_control_slave_translator:uav_read
	wire         sysid_control_slave_agent_m0_readdatavalid;                              // sysid_control_slave_translator:uav_readdatavalid -> sysid_control_slave_agent:m0_readdatavalid
	wire         sysid_control_slave_agent_m0_lock;                                       // sysid_control_slave_agent:m0_lock -> sysid_control_slave_translator:uav_lock
	wire  [31:0] sysid_control_slave_agent_m0_writedata;                                  // sysid_control_slave_agent:m0_writedata -> sysid_control_slave_translator:uav_writedata
	wire         sysid_control_slave_agent_m0_write;                                      // sysid_control_slave_agent:m0_write -> sysid_control_slave_translator:uav_write
	wire   [2:0] sysid_control_slave_agent_m0_burstcount;                                 // sysid_control_slave_agent:m0_burstcount -> sysid_control_slave_translator:uav_burstcount
	wire         sysid_control_slave_agent_rf_source_valid;                               // sysid_control_slave_agent:rf_source_valid -> sysid_control_slave_agent_rsp_fifo:in_valid
	wire  [92:0] sysid_control_slave_agent_rf_source_data;                                // sysid_control_slave_agent:rf_source_data -> sysid_control_slave_agent_rsp_fifo:in_data
	wire         sysid_control_slave_agent_rf_source_ready;                               // sysid_control_slave_agent_rsp_fifo:in_ready -> sysid_control_slave_agent:rf_source_ready
	wire         sysid_control_slave_agent_rf_source_startofpacket;                       // sysid_control_slave_agent:rf_source_startofpacket -> sysid_control_slave_agent_rsp_fifo:in_startofpacket
	wire         sysid_control_slave_agent_rf_source_endofpacket;                         // sysid_control_slave_agent:rf_source_endofpacket -> sysid_control_slave_agent_rsp_fifo:in_endofpacket
	wire         sysid_control_slave_agent_rsp_fifo_out_valid;                            // sysid_control_slave_agent_rsp_fifo:out_valid -> sysid_control_slave_agent:rf_sink_valid
	wire  [92:0] sysid_control_slave_agent_rsp_fifo_out_data;                             // sysid_control_slave_agent_rsp_fifo:out_data -> sysid_control_slave_agent:rf_sink_data
	wire         sysid_control_slave_agent_rsp_fifo_out_ready;                            // sysid_control_slave_agent:rf_sink_ready -> sysid_control_slave_agent_rsp_fifo:out_ready
	wire         sysid_control_slave_agent_rsp_fifo_out_startofpacket;                    // sysid_control_slave_agent_rsp_fifo:out_startofpacket -> sysid_control_slave_agent:rf_sink_startofpacket
	wire         sysid_control_slave_agent_rsp_fifo_out_endofpacket;                      // sysid_control_slave_agent_rsp_fifo:out_endofpacket -> sysid_control_slave_agent:rf_sink_endofpacket
	wire         cmd_mux_src_valid;                                                       // cmd_mux:src_valid -> sysid_control_slave_agent:cp_valid
	wire  [91:0] cmd_mux_src_data;                                                        // cmd_mux:src_data -> sysid_control_slave_agent:cp_data
	wire         cmd_mux_src_ready;                                                       // sysid_control_slave_agent:cp_ready -> cmd_mux:src_ready
	wire   [1:0] cmd_mux_src_channel;                                                     // cmd_mux:src_channel -> sysid_control_slave_agent:cp_channel
	wire         cmd_mux_src_startofpacket;                                               // cmd_mux:src_startofpacket -> sysid_control_slave_agent:cp_startofpacket
	wire         cmd_mux_src_endofpacket;                                                 // cmd_mux:src_endofpacket -> sysid_control_slave_agent:cp_endofpacket
	wire  [31:0] cy7c67200_if_0_hpi_agent_m0_readdata;                                    // CY7C67200_IF_0_hpi_translator:uav_readdata -> CY7C67200_IF_0_hpi_agent:m0_readdata
	wire         cy7c67200_if_0_hpi_agent_m0_waitrequest;                                 // CY7C67200_IF_0_hpi_translator:uav_waitrequest -> CY7C67200_IF_0_hpi_agent:m0_waitrequest
	wire         cy7c67200_if_0_hpi_agent_m0_debugaccess;                                 // CY7C67200_IF_0_hpi_agent:m0_debugaccess -> CY7C67200_IF_0_hpi_translator:uav_debugaccess
	wire  [21:0] cy7c67200_if_0_hpi_agent_m0_address;                                     // CY7C67200_IF_0_hpi_agent:m0_address -> CY7C67200_IF_0_hpi_translator:uav_address
	wire   [3:0] cy7c67200_if_0_hpi_agent_m0_byteenable;                                  // CY7C67200_IF_0_hpi_agent:m0_byteenable -> CY7C67200_IF_0_hpi_translator:uav_byteenable
	wire         cy7c67200_if_0_hpi_agent_m0_read;                                        // CY7C67200_IF_0_hpi_agent:m0_read -> CY7C67200_IF_0_hpi_translator:uav_read
	wire         cy7c67200_if_0_hpi_agent_m0_readdatavalid;                               // CY7C67200_IF_0_hpi_translator:uav_readdatavalid -> CY7C67200_IF_0_hpi_agent:m0_readdatavalid
	wire         cy7c67200_if_0_hpi_agent_m0_lock;                                        // CY7C67200_IF_0_hpi_agent:m0_lock -> CY7C67200_IF_0_hpi_translator:uav_lock
	wire  [31:0] cy7c67200_if_0_hpi_agent_m0_writedata;                                   // CY7C67200_IF_0_hpi_agent:m0_writedata -> CY7C67200_IF_0_hpi_translator:uav_writedata
	wire         cy7c67200_if_0_hpi_agent_m0_write;                                       // CY7C67200_IF_0_hpi_agent:m0_write -> CY7C67200_IF_0_hpi_translator:uav_write
	wire   [2:0] cy7c67200_if_0_hpi_agent_m0_burstcount;                                  // CY7C67200_IF_0_hpi_agent:m0_burstcount -> CY7C67200_IF_0_hpi_translator:uav_burstcount
	wire         cy7c67200_if_0_hpi_agent_rf_source_valid;                                // CY7C67200_IF_0_hpi_agent:rf_source_valid -> CY7C67200_IF_0_hpi_agent_rsp_fifo:in_valid
	wire  [92:0] cy7c67200_if_0_hpi_agent_rf_source_data;                                 // CY7C67200_IF_0_hpi_agent:rf_source_data -> CY7C67200_IF_0_hpi_agent_rsp_fifo:in_data
	wire         cy7c67200_if_0_hpi_agent_rf_source_ready;                                // CY7C67200_IF_0_hpi_agent_rsp_fifo:in_ready -> CY7C67200_IF_0_hpi_agent:rf_source_ready
	wire         cy7c67200_if_0_hpi_agent_rf_source_startofpacket;                        // CY7C67200_IF_0_hpi_agent:rf_source_startofpacket -> CY7C67200_IF_0_hpi_agent_rsp_fifo:in_startofpacket
	wire         cy7c67200_if_0_hpi_agent_rf_source_endofpacket;                          // CY7C67200_IF_0_hpi_agent:rf_source_endofpacket -> CY7C67200_IF_0_hpi_agent_rsp_fifo:in_endofpacket
	wire         cy7c67200_if_0_hpi_agent_rsp_fifo_out_valid;                             // CY7C67200_IF_0_hpi_agent_rsp_fifo:out_valid -> CY7C67200_IF_0_hpi_agent:rf_sink_valid
	wire  [92:0] cy7c67200_if_0_hpi_agent_rsp_fifo_out_data;                              // CY7C67200_IF_0_hpi_agent_rsp_fifo:out_data -> CY7C67200_IF_0_hpi_agent:rf_sink_data
	wire         cy7c67200_if_0_hpi_agent_rsp_fifo_out_ready;                             // CY7C67200_IF_0_hpi_agent:rf_sink_ready -> CY7C67200_IF_0_hpi_agent_rsp_fifo:out_ready
	wire         cy7c67200_if_0_hpi_agent_rsp_fifo_out_startofpacket;                     // CY7C67200_IF_0_hpi_agent_rsp_fifo:out_startofpacket -> CY7C67200_IF_0_hpi_agent:rf_sink_startofpacket
	wire         cy7c67200_if_0_hpi_agent_rsp_fifo_out_endofpacket;                       // CY7C67200_IF_0_hpi_agent_rsp_fifo:out_endofpacket -> CY7C67200_IF_0_hpi_agent:rf_sink_endofpacket
	wire         cmd_mux_001_src_valid;                                                   // cmd_mux_001:src_valid -> CY7C67200_IF_0_hpi_agent:cp_valid
	wire  [91:0] cmd_mux_001_src_data;                                                    // cmd_mux_001:src_data -> CY7C67200_IF_0_hpi_agent:cp_data
	wire         cmd_mux_001_src_ready;                                                   // CY7C67200_IF_0_hpi_agent:cp_ready -> cmd_mux_001:src_ready
	wire   [1:0] cmd_mux_001_src_channel;                                                 // cmd_mux_001:src_channel -> CY7C67200_IF_0_hpi_agent:cp_channel
	wire         cmd_mux_001_src_startofpacket;                                           // cmd_mux_001:src_startofpacket -> CY7C67200_IF_0_hpi_agent:cp_startofpacket
	wire         cmd_mux_001_src_endofpacket;                                             // cmd_mux_001:src_endofpacket -> CY7C67200_IF_0_hpi_agent:cp_endofpacket
	wire         clock_crossing_io_m0_agent_cp_valid;                                     // clock_crossing_io_m0_agent:cp_valid -> router:sink_valid
	wire  [91:0] clock_crossing_io_m0_agent_cp_data;                                      // clock_crossing_io_m0_agent:cp_data -> router:sink_data
	wire         clock_crossing_io_m0_agent_cp_ready;                                     // router:sink_ready -> clock_crossing_io_m0_agent:cp_ready
	wire         clock_crossing_io_m0_agent_cp_startofpacket;                             // clock_crossing_io_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire         clock_crossing_io_m0_agent_cp_endofpacket;                               // clock_crossing_io_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire         sysid_control_slave_agent_rp_valid;                                      // sysid_control_slave_agent:rp_valid -> router_001:sink_valid
	wire  [91:0] sysid_control_slave_agent_rp_data;                                       // sysid_control_slave_agent:rp_data -> router_001:sink_data
	wire         sysid_control_slave_agent_rp_ready;                                      // router_001:sink_ready -> sysid_control_slave_agent:rp_ready
	wire         sysid_control_slave_agent_rp_startofpacket;                              // sysid_control_slave_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire         sysid_control_slave_agent_rp_endofpacket;                                // sysid_control_slave_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire         router_001_src_valid;                                                    // router_001:src_valid -> rsp_demux:sink_valid
	wire  [91:0] router_001_src_data;                                                     // router_001:src_data -> rsp_demux:sink_data
	wire         router_001_src_ready;                                                    // rsp_demux:sink_ready -> router_001:src_ready
	wire   [1:0] router_001_src_channel;                                                  // router_001:src_channel -> rsp_demux:sink_channel
	wire         router_001_src_startofpacket;                                            // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire         router_001_src_endofpacket;                                              // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire         cy7c67200_if_0_hpi_agent_rp_valid;                                       // CY7C67200_IF_0_hpi_agent:rp_valid -> router_002:sink_valid
	wire  [91:0] cy7c67200_if_0_hpi_agent_rp_data;                                        // CY7C67200_IF_0_hpi_agent:rp_data -> router_002:sink_data
	wire         cy7c67200_if_0_hpi_agent_rp_ready;                                       // router_002:sink_ready -> CY7C67200_IF_0_hpi_agent:rp_ready
	wire         cy7c67200_if_0_hpi_agent_rp_startofpacket;                               // CY7C67200_IF_0_hpi_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire         cy7c67200_if_0_hpi_agent_rp_endofpacket;                                 // CY7C67200_IF_0_hpi_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire         router_002_src_valid;                                                    // router_002:src_valid -> rsp_demux_001:sink_valid
	wire  [91:0] router_002_src_data;                                                     // router_002:src_data -> rsp_demux_001:sink_data
	wire         router_002_src_ready;                                                    // rsp_demux_001:sink_ready -> router_002:src_ready
	wire   [1:0] router_002_src_channel;                                                  // router_002:src_channel -> rsp_demux_001:sink_channel
	wire         router_002_src_startofpacket;                                            // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire         router_002_src_endofpacket;                                              // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire         router_src_valid;                                                        // router:src_valid -> clock_crossing_io_m0_limiter:cmd_sink_valid
	wire  [91:0] router_src_data;                                                         // router:src_data -> clock_crossing_io_m0_limiter:cmd_sink_data
	wire         router_src_ready;                                                        // clock_crossing_io_m0_limiter:cmd_sink_ready -> router:src_ready
	wire   [1:0] router_src_channel;                                                      // router:src_channel -> clock_crossing_io_m0_limiter:cmd_sink_channel
	wire         router_src_startofpacket;                                                // router:src_startofpacket -> clock_crossing_io_m0_limiter:cmd_sink_startofpacket
	wire         router_src_endofpacket;                                                  // router:src_endofpacket -> clock_crossing_io_m0_limiter:cmd_sink_endofpacket
	wire  [91:0] clock_crossing_io_m0_limiter_cmd_src_data;                               // clock_crossing_io_m0_limiter:cmd_src_data -> cmd_demux:sink_data
	wire         clock_crossing_io_m0_limiter_cmd_src_ready;                              // cmd_demux:sink_ready -> clock_crossing_io_m0_limiter:cmd_src_ready
	wire   [1:0] clock_crossing_io_m0_limiter_cmd_src_channel;                            // clock_crossing_io_m0_limiter:cmd_src_channel -> cmd_demux:sink_channel
	wire         clock_crossing_io_m0_limiter_cmd_src_startofpacket;                      // clock_crossing_io_m0_limiter:cmd_src_startofpacket -> cmd_demux:sink_startofpacket
	wire         clock_crossing_io_m0_limiter_cmd_src_endofpacket;                        // clock_crossing_io_m0_limiter:cmd_src_endofpacket -> cmd_demux:sink_endofpacket
	wire         rsp_mux_src_valid;                                                       // rsp_mux:src_valid -> clock_crossing_io_m0_limiter:rsp_sink_valid
	wire  [91:0] rsp_mux_src_data;                                                        // rsp_mux:src_data -> clock_crossing_io_m0_limiter:rsp_sink_data
	wire         rsp_mux_src_ready;                                                       // clock_crossing_io_m0_limiter:rsp_sink_ready -> rsp_mux:src_ready
	wire   [1:0] rsp_mux_src_channel;                                                     // rsp_mux:src_channel -> clock_crossing_io_m0_limiter:rsp_sink_channel
	wire         rsp_mux_src_startofpacket;                                               // rsp_mux:src_startofpacket -> clock_crossing_io_m0_limiter:rsp_sink_startofpacket
	wire         rsp_mux_src_endofpacket;                                                 // rsp_mux:src_endofpacket -> clock_crossing_io_m0_limiter:rsp_sink_endofpacket
	wire         clock_crossing_io_m0_limiter_rsp_src_valid;                              // clock_crossing_io_m0_limiter:rsp_src_valid -> clock_crossing_io_m0_agent:rp_valid
	wire  [91:0] clock_crossing_io_m0_limiter_rsp_src_data;                               // clock_crossing_io_m0_limiter:rsp_src_data -> clock_crossing_io_m0_agent:rp_data
	wire         clock_crossing_io_m0_limiter_rsp_src_ready;                              // clock_crossing_io_m0_agent:rp_ready -> clock_crossing_io_m0_limiter:rsp_src_ready
	wire   [1:0] clock_crossing_io_m0_limiter_rsp_src_channel;                            // clock_crossing_io_m0_limiter:rsp_src_channel -> clock_crossing_io_m0_agent:rp_channel
	wire         clock_crossing_io_m0_limiter_rsp_src_startofpacket;                      // clock_crossing_io_m0_limiter:rsp_src_startofpacket -> clock_crossing_io_m0_agent:rp_startofpacket
	wire         clock_crossing_io_m0_limiter_rsp_src_endofpacket;                        // clock_crossing_io_m0_limiter:rsp_src_endofpacket -> clock_crossing_io_m0_agent:rp_endofpacket
	wire         cmd_demux_src0_valid;                                                    // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [91:0] cmd_demux_src0_data;                                                     // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire         cmd_demux_src0_ready;                                                    // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire   [1:0] cmd_demux_src0_channel;                                                  // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire         cmd_demux_src0_startofpacket;                                            // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire         cmd_demux_src0_endofpacket;                                              // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire         cmd_demux_src1_valid;                                                    // cmd_demux:src1_valid -> cmd_mux_001:sink0_valid
	wire  [91:0] cmd_demux_src1_data;                                                     // cmd_demux:src1_data -> cmd_mux_001:sink0_data
	wire         cmd_demux_src1_ready;                                                    // cmd_mux_001:sink0_ready -> cmd_demux:src1_ready
	wire   [1:0] cmd_demux_src1_channel;                                                  // cmd_demux:src1_channel -> cmd_mux_001:sink0_channel
	wire         cmd_demux_src1_startofpacket;                                            // cmd_demux:src1_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire         cmd_demux_src1_endofpacket;                                              // cmd_demux:src1_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire         rsp_demux_src0_valid;                                                    // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [91:0] rsp_demux_src0_data;                                                     // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire         rsp_demux_src0_ready;                                                    // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire   [1:0] rsp_demux_src0_channel;                                                  // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire         rsp_demux_src0_startofpacket;                                            // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire         rsp_demux_src0_endofpacket;                                              // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire         rsp_demux_001_src0_valid;                                                // rsp_demux_001:src0_valid -> rsp_mux:sink1_valid
	wire  [91:0] rsp_demux_001_src0_data;                                                 // rsp_demux_001:src0_data -> rsp_mux:sink1_data
	wire         rsp_demux_001_src0_ready;                                                // rsp_mux:sink1_ready -> rsp_demux_001:src0_ready
	wire   [1:0] rsp_demux_001_src0_channel;                                              // rsp_demux_001:src0_channel -> rsp_mux:sink1_channel
	wire         rsp_demux_001_src0_startofpacket;                                        // rsp_demux_001:src0_startofpacket -> rsp_mux:sink1_startofpacket
	wire         rsp_demux_001_src0_endofpacket;                                          // rsp_demux_001:src0_endofpacket -> rsp_mux:sink1_endofpacket
	wire   [1:0] clock_crossing_io_m0_limiter_cmd_valid_data;                             // clock_crossing_io_m0_limiter:cmd_src_valid -> cmd_demux:sink_valid
	wire         sysid_control_slave_agent_rdata_fifo_src_valid;                          // sysid_control_slave_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [33:0] sysid_control_slave_agent_rdata_fifo_src_data;                           // sysid_control_slave_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         sysid_control_slave_agent_rdata_fifo_src_ready;                          // avalon_st_adapter:in_0_ready -> sysid_control_slave_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                           // avalon_st_adapter:out_0_valid -> sysid_control_slave_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_out_0_data;                                            // avalon_st_adapter:out_0_data -> sysid_control_slave_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                           // sysid_control_slave_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                           // avalon_st_adapter:out_0_error -> sysid_control_slave_agent:rdata_fifo_sink_error
	wire         cy7c67200_if_0_hpi_agent_rdata_fifo_src_valid;                           // CY7C67200_IF_0_hpi_agent:rdata_fifo_src_valid -> avalon_st_adapter_001:in_0_valid
	wire  [33:0] cy7c67200_if_0_hpi_agent_rdata_fifo_src_data;                            // CY7C67200_IF_0_hpi_agent:rdata_fifo_src_data -> avalon_st_adapter_001:in_0_data
	wire         cy7c67200_if_0_hpi_agent_rdata_fifo_src_ready;                           // avalon_st_adapter_001:in_0_ready -> CY7C67200_IF_0_hpi_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_001_out_0_valid;                                       // avalon_st_adapter_001:out_0_valid -> CY7C67200_IF_0_hpi_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_001_out_0_data;                                        // avalon_st_adapter_001:out_0_data -> CY7C67200_IF_0_hpi_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_001_out_0_ready;                                       // CY7C67200_IF_0_hpi_agent:rdata_fifo_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire   [0:0] avalon_st_adapter_001_out_0_error;                                       // avalon_st_adapter_001:out_0_error -> CY7C67200_IF_0_hpi_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (22),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (22),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) clock_crossing_io_m0_translator (
		.clk                    (pll_c2_clk),                                                              //                       clk.clk
		.reset                  (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset),                  //                     reset.reset
		.uav_address            (clock_crossing_io_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (clock_crossing_io_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (clock_crossing_io_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (clock_crossing_io_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (clock_crossing_io_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (clock_crossing_io_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (clock_crossing_io_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (clock_crossing_io_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (clock_crossing_io_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (clock_crossing_io_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (clock_crossing_io_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (clock_crossing_io_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (clock_crossing_io_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (clock_crossing_io_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (clock_crossing_io_m0_byteenable),                                         //                          .byteenable
		.av_read                (clock_crossing_io_m0_read),                                               //                          .read
		.av_readdata            (clock_crossing_io_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (clock_crossing_io_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (clock_crossing_io_m0_write),                                              //                          .write
		.av_writedata           (clock_crossing_io_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (clock_crossing_io_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                    //               (terminated)
		.av_begintransfer       (1'b0),                                                                    //               (terminated)
		.av_chipselect          (1'b0),                                                                    //               (terminated)
		.av_lock                (1'b0),                                                                    //               (terminated)
		.uav_clken              (),                                                                        //               (terminated)
		.av_clken               (1'b1),                                                                    //               (terminated)
		.uav_response           (2'b00),                                                                   //               (terminated)
		.av_response            (),                                                                        //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                    //               (terminated)
		.av_writeresponsevalid  ()                                                                         //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (22),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sysid_control_slave_translator (
		.clk                    (pll_c2_clk),                                             //                      clk.clk
		.reset                  (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (sysid_control_slave_agent_m0_address),                   // avalon_universal_slave_0.address
		.uav_burstcount         (sysid_control_slave_agent_m0_burstcount),                //                         .burstcount
		.uav_read               (sysid_control_slave_agent_m0_read),                      //                         .read
		.uav_write              (sysid_control_slave_agent_m0_write),                     //                         .write
		.uav_waitrequest        (sysid_control_slave_agent_m0_waitrequest),               //                         .waitrequest
		.uav_readdatavalid      (sysid_control_slave_agent_m0_readdatavalid),             //                         .readdatavalid
		.uav_byteenable         (sysid_control_slave_agent_m0_byteenable),                //                         .byteenable
		.uav_readdata           (sysid_control_slave_agent_m0_readdata),                  //                         .readdata
		.uav_writedata          (sysid_control_slave_agent_m0_writedata),                 //                         .writedata
		.uav_lock               (sysid_control_slave_agent_m0_lock),                      //                         .lock
		.uav_debugaccess        (sysid_control_slave_agent_m0_debugaccess),               //                         .debugaccess
		.av_address             (sysid_control_slave_address),                            //      avalon_anti_slave_0.address
		.av_readdata            (sysid_control_slave_readdata),                           //                         .readdata
		.av_write               (),                                                       //              (terminated)
		.av_read                (),                                                       //              (terminated)
		.av_writedata           (),                                                       //              (terminated)
		.av_begintransfer       (),                                                       //              (terminated)
		.av_beginbursttransfer  (),                                                       //              (terminated)
		.av_burstcount          (),                                                       //              (terminated)
		.av_byteenable          (),                                                       //              (terminated)
		.av_readdatavalid       (1'b0),                                                   //              (terminated)
		.av_waitrequest         (1'b0),                                                   //              (terminated)
		.av_writebyteenable     (),                                                       //              (terminated)
		.av_lock                (),                                                       //              (terminated)
		.av_chipselect          (),                                                       //              (terminated)
		.av_clken               (),                                                       //              (terminated)
		.uav_clken              (1'b0),                                                   //              (terminated)
		.av_debugaccess         (),                                                       //              (terminated)
		.av_outputenable        (),                                                       //              (terminated)
		.uav_response           (),                                                       //              (terminated)
		.av_response            (2'b00),                                                  //              (terminated)
		.uav_writeresponsevalid (),                                                       //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                    //              (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (22),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (2),
		.AV_WRITE_WAIT_CYCLES           (2),
		.AV_SETUP_WAIT_CYCLES           (2),
		.AV_DATA_HOLD_CYCLES            (2)
	) cy7c67200_if_0_hpi_translator (
		.clk                    (pll_c2_clk),                                             //                      clk.clk
		.reset                  (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (cy7c67200_if_0_hpi_agent_m0_address),                    // avalon_universal_slave_0.address
		.uav_burstcount         (cy7c67200_if_0_hpi_agent_m0_burstcount),                 //                         .burstcount
		.uav_read               (cy7c67200_if_0_hpi_agent_m0_read),                       //                         .read
		.uav_write              (cy7c67200_if_0_hpi_agent_m0_write),                      //                         .write
		.uav_waitrequest        (cy7c67200_if_0_hpi_agent_m0_waitrequest),                //                         .waitrequest
		.uav_readdatavalid      (cy7c67200_if_0_hpi_agent_m0_readdatavalid),              //                         .readdatavalid
		.uav_byteenable         (cy7c67200_if_0_hpi_agent_m0_byteenable),                 //                         .byteenable
		.uav_readdata           (cy7c67200_if_0_hpi_agent_m0_readdata),                   //                         .readdata
		.uav_writedata          (cy7c67200_if_0_hpi_agent_m0_writedata),                  //                         .writedata
		.uav_lock               (cy7c67200_if_0_hpi_agent_m0_lock),                       //                         .lock
		.uav_debugaccess        (cy7c67200_if_0_hpi_agent_m0_debugaccess),                //                         .debugaccess
		.av_address             (CY7C67200_IF_0_hpi_address),                             //      avalon_anti_slave_0.address
		.av_write               (CY7C67200_IF_0_hpi_write),                               //                         .write
		.av_read                (CY7C67200_IF_0_hpi_read),                                //                         .read
		.av_readdata            (CY7C67200_IF_0_hpi_readdata),                            //                         .readdata
		.av_writedata           (CY7C67200_IF_0_hpi_writedata),                           //                         .writedata
		.av_chipselect          (CY7C67200_IF_0_hpi_chipselect),                          //                         .chipselect
		.av_begintransfer       (),                                                       //              (terminated)
		.av_beginbursttransfer  (),                                                       //              (terminated)
		.av_burstcount          (),                                                       //              (terminated)
		.av_byteenable          (),                                                       //              (terminated)
		.av_readdatavalid       (1'b0),                                                   //              (terminated)
		.av_waitrequest         (1'b0),                                                   //              (terminated)
		.av_writebyteenable     (),                                                       //              (terminated)
		.av_lock                (),                                                       //              (terminated)
		.av_clken               (),                                                       //              (terminated)
		.uav_clken              (1'b0),                                                   //              (terminated)
		.av_debugaccess         (),                                                       //              (terminated)
		.av_outputenable        (),                                                       //              (terminated)
		.uav_response           (),                                                       //              (terminated)
		.av_response            (2'b00),                                                  //              (terminated)
		.uav_writeresponsevalid (),                                                       //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                    //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (91),
		.PKT_ORI_BURST_SIZE_L      (89),
		.PKT_RESPONSE_STATUS_H     (88),
		.PKT_RESPONSE_STATUS_L     (87),
		.PKT_QOS_H                 (76),
		.PKT_QOS_L                 (76),
		.PKT_DATA_SIDEBAND_H       (74),
		.PKT_DATA_SIDEBAND_L       (74),
		.PKT_ADDR_SIDEBAND_H       (73),
		.PKT_ADDR_SIDEBAND_L       (73),
		.PKT_BURST_TYPE_H          (72),
		.PKT_BURST_TYPE_L          (71),
		.PKT_CACHE_H               (86),
		.PKT_CACHE_L               (83),
		.PKT_THREAD_ID_H           (79),
		.PKT_THREAD_ID_L           (79),
		.PKT_BURST_SIZE_H          (70),
		.PKT_BURST_SIZE_L          (68),
		.PKT_TRANS_EXCLUSIVE       (63),
		.PKT_TRANS_LOCK            (62),
		.PKT_BEGIN_BURST           (75),
		.PKT_PROTECTION_H          (82),
		.PKT_PROTECTION_L          (80),
		.PKT_BURSTWRAP_H           (67),
		.PKT_BURSTWRAP_L           (67),
		.PKT_BYTE_CNT_H            (66),
		.PKT_BYTE_CNT_L            (64),
		.PKT_ADDR_H                (57),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (58),
		.PKT_TRANS_POSTED          (59),
		.PKT_TRANS_WRITE           (60),
		.PKT_TRANS_READ            (61),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (77),
		.PKT_SRC_ID_L              (77),
		.PKT_DEST_ID_H             (78),
		.PKT_DEST_ID_L             (78),
		.ST_DATA_W                 (92),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) clock_crossing_io_m0_agent (
		.clk                   (pll_c2_clk),                                                              //       clk.clk
		.reset                 (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset),                  // clk_reset.reset
		.av_address            (clock_crossing_io_m0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (clock_crossing_io_m0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (clock_crossing_io_m0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (clock_crossing_io_m0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (clock_crossing_io_m0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (clock_crossing_io_m0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (clock_crossing_io_m0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (clock_crossing_io_m0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (clock_crossing_io_m0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (clock_crossing_io_m0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (clock_crossing_io_m0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (clock_crossing_io_m0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (clock_crossing_io_m0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (clock_crossing_io_m0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (clock_crossing_io_m0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (clock_crossing_io_m0_agent_cp_ready),                                     //          .ready
		.rp_valid              (clock_crossing_io_m0_limiter_rsp_src_valid),                              //        rp.valid
		.rp_data               (clock_crossing_io_m0_limiter_rsp_src_data),                               //          .data
		.rp_channel            (clock_crossing_io_m0_limiter_rsp_src_channel),                            //          .channel
		.rp_startofpacket      (clock_crossing_io_m0_limiter_rsp_src_startofpacket),                      //          .startofpacket
		.rp_endofpacket        (clock_crossing_io_m0_limiter_rsp_src_endofpacket),                        //          .endofpacket
		.rp_ready              (clock_crossing_io_m0_limiter_rsp_src_ready),                              //          .ready
		.av_response           (),                                                                        // (terminated)
		.av_writeresponsevalid ()                                                                         // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (91),
		.PKT_ORI_BURST_SIZE_L      (89),
		.PKT_RESPONSE_STATUS_H     (88),
		.PKT_RESPONSE_STATUS_L     (87),
		.PKT_BURST_SIZE_H          (70),
		.PKT_BURST_SIZE_L          (68),
		.PKT_TRANS_LOCK            (62),
		.PKT_BEGIN_BURST           (75),
		.PKT_PROTECTION_H          (82),
		.PKT_PROTECTION_L          (80),
		.PKT_BURSTWRAP_H           (67),
		.PKT_BURSTWRAP_L           (67),
		.PKT_BYTE_CNT_H            (66),
		.PKT_BYTE_CNT_L            (64),
		.PKT_ADDR_H                (57),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (58),
		.PKT_TRANS_POSTED          (59),
		.PKT_TRANS_WRITE           (60),
		.PKT_TRANS_READ            (61),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (77),
		.PKT_SRC_ID_L              (77),
		.PKT_DEST_ID_H             (78),
		.PKT_DEST_ID_L             (78),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (92),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) sysid_control_slave_agent (
		.clk                     (pll_c2_clk),                                             //             clk.clk
		.reset                   (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (sysid_control_slave_agent_m0_address),                   //              m0.address
		.m0_burstcount           (sysid_control_slave_agent_m0_burstcount),                //                .burstcount
		.m0_byteenable           (sysid_control_slave_agent_m0_byteenable),                //                .byteenable
		.m0_debugaccess          (sysid_control_slave_agent_m0_debugaccess),               //                .debugaccess
		.m0_lock                 (sysid_control_slave_agent_m0_lock),                      //                .lock
		.m0_readdata             (sysid_control_slave_agent_m0_readdata),                  //                .readdata
		.m0_readdatavalid        (sysid_control_slave_agent_m0_readdatavalid),             //                .readdatavalid
		.m0_read                 (sysid_control_slave_agent_m0_read),                      //                .read
		.m0_waitrequest          (sysid_control_slave_agent_m0_waitrequest),               //                .waitrequest
		.m0_writedata            (sysid_control_slave_agent_m0_writedata),                 //                .writedata
		.m0_write                (sysid_control_slave_agent_m0_write),                     //                .write
		.rp_endofpacket          (sysid_control_slave_agent_rp_endofpacket),               //              rp.endofpacket
		.rp_ready                (sysid_control_slave_agent_rp_ready),                     //                .ready
		.rp_valid                (sysid_control_slave_agent_rp_valid),                     //                .valid
		.rp_data                 (sysid_control_slave_agent_rp_data),                      //                .data
		.rp_startofpacket        (sysid_control_slave_agent_rp_startofpacket),             //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                      //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                      //                .valid
		.cp_data                 (cmd_mux_src_data),                                       //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                              //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                    //                .channel
		.rf_sink_ready           (sysid_control_slave_agent_rsp_fifo_out_ready),           //         rf_sink.ready
		.rf_sink_valid           (sysid_control_slave_agent_rsp_fifo_out_valid),           //                .valid
		.rf_sink_startofpacket   (sysid_control_slave_agent_rsp_fifo_out_startofpacket),   //                .startofpacket
		.rf_sink_endofpacket     (sysid_control_slave_agent_rsp_fifo_out_endofpacket),     //                .endofpacket
		.rf_sink_data            (sysid_control_slave_agent_rsp_fifo_out_data),            //                .data
		.rf_source_ready         (sysid_control_slave_agent_rf_source_ready),              //       rf_source.ready
		.rf_source_valid         (sysid_control_slave_agent_rf_source_valid),              //                .valid
		.rf_source_startofpacket (sysid_control_slave_agent_rf_source_startofpacket),      //                .startofpacket
		.rf_source_endofpacket   (sysid_control_slave_agent_rf_source_endofpacket),        //                .endofpacket
		.rf_source_data          (sysid_control_slave_agent_rf_source_data),               //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                          // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                          //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                           //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                          //                .error
		.rdata_fifo_src_ready    (sysid_control_slave_agent_rdata_fifo_src_ready),         //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (sysid_control_slave_agent_rdata_fifo_src_valid),         //                .valid
		.rdata_fifo_src_data     (sysid_control_slave_agent_rdata_fifo_src_data),          //                .data
		.m0_response             (2'b00),                                                  //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                    //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (93),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sysid_control_slave_agent_rsp_fifo (
		.clk               (pll_c2_clk),                                             //       clk.clk
		.reset             (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (sysid_control_slave_agent_rf_source_data),               //        in.data
		.in_valid          (sysid_control_slave_agent_rf_source_valid),              //          .valid
		.in_ready          (sysid_control_slave_agent_rf_source_ready),              //          .ready
		.in_startofpacket  (sysid_control_slave_agent_rf_source_startofpacket),      //          .startofpacket
		.in_endofpacket    (sysid_control_slave_agent_rf_source_endofpacket),        //          .endofpacket
		.out_data          (sysid_control_slave_agent_rsp_fifo_out_data),            //       out.data
		.out_valid         (sysid_control_slave_agent_rsp_fifo_out_valid),           //          .valid
		.out_ready         (sysid_control_slave_agent_rsp_fifo_out_ready),           //          .ready
		.out_startofpacket (sysid_control_slave_agent_rsp_fifo_out_startofpacket),   //          .startofpacket
		.out_endofpacket   (sysid_control_slave_agent_rsp_fifo_out_endofpacket),     //          .endofpacket
		.csr_address       (2'b00),                                                  // (terminated)
		.csr_read          (1'b0),                                                   // (terminated)
		.csr_write         (1'b0),                                                   // (terminated)
		.csr_readdata      (),                                                       // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                   // (terminated)
		.almost_full_data  (),                                                       // (terminated)
		.almost_empty_data (),                                                       // (terminated)
		.in_empty          (1'b0),                                                   // (terminated)
		.out_empty         (),                                                       // (terminated)
		.in_error          (1'b0),                                                   // (terminated)
		.out_error         (),                                                       // (terminated)
		.in_channel        (1'b0),                                                   // (terminated)
		.out_channel       ()                                                        // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (91),
		.PKT_ORI_BURST_SIZE_L      (89),
		.PKT_RESPONSE_STATUS_H     (88),
		.PKT_RESPONSE_STATUS_L     (87),
		.PKT_BURST_SIZE_H          (70),
		.PKT_BURST_SIZE_L          (68),
		.PKT_TRANS_LOCK            (62),
		.PKT_BEGIN_BURST           (75),
		.PKT_PROTECTION_H          (82),
		.PKT_PROTECTION_L          (80),
		.PKT_BURSTWRAP_H           (67),
		.PKT_BURSTWRAP_L           (67),
		.PKT_BYTE_CNT_H            (66),
		.PKT_BYTE_CNT_L            (64),
		.PKT_ADDR_H                (57),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (58),
		.PKT_TRANS_POSTED          (59),
		.PKT_TRANS_WRITE           (60),
		.PKT_TRANS_READ            (61),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (77),
		.PKT_SRC_ID_L              (77),
		.PKT_DEST_ID_H             (78),
		.PKT_DEST_ID_L             (78),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (92),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) cy7c67200_if_0_hpi_agent (
		.clk                     (pll_c2_clk),                                             //             clk.clk
		.reset                   (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (cy7c67200_if_0_hpi_agent_m0_address),                    //              m0.address
		.m0_burstcount           (cy7c67200_if_0_hpi_agent_m0_burstcount),                 //                .burstcount
		.m0_byteenable           (cy7c67200_if_0_hpi_agent_m0_byteenable),                 //                .byteenable
		.m0_debugaccess          (cy7c67200_if_0_hpi_agent_m0_debugaccess),                //                .debugaccess
		.m0_lock                 (cy7c67200_if_0_hpi_agent_m0_lock),                       //                .lock
		.m0_readdata             (cy7c67200_if_0_hpi_agent_m0_readdata),                   //                .readdata
		.m0_readdatavalid        (cy7c67200_if_0_hpi_agent_m0_readdatavalid),              //                .readdatavalid
		.m0_read                 (cy7c67200_if_0_hpi_agent_m0_read),                       //                .read
		.m0_waitrequest          (cy7c67200_if_0_hpi_agent_m0_waitrequest),                //                .waitrequest
		.m0_writedata            (cy7c67200_if_0_hpi_agent_m0_writedata),                  //                .writedata
		.m0_write                (cy7c67200_if_0_hpi_agent_m0_write),                      //                .write
		.rp_endofpacket          (cy7c67200_if_0_hpi_agent_rp_endofpacket),                //              rp.endofpacket
		.rp_ready                (cy7c67200_if_0_hpi_agent_rp_ready),                      //                .ready
		.rp_valid                (cy7c67200_if_0_hpi_agent_rp_valid),                      //                .valid
		.rp_data                 (cy7c67200_if_0_hpi_agent_rp_data),                       //                .data
		.rp_startofpacket        (cy7c67200_if_0_hpi_agent_rp_startofpacket),              //                .startofpacket
		.cp_ready                (cmd_mux_001_src_ready),                                  //              cp.ready
		.cp_valid                (cmd_mux_001_src_valid),                                  //                .valid
		.cp_data                 (cmd_mux_001_src_data),                                   //                .data
		.cp_startofpacket        (cmd_mux_001_src_startofpacket),                          //                .startofpacket
		.cp_endofpacket          (cmd_mux_001_src_endofpacket),                            //                .endofpacket
		.cp_channel              (cmd_mux_001_src_channel),                                //                .channel
		.rf_sink_ready           (cy7c67200_if_0_hpi_agent_rsp_fifo_out_ready),            //         rf_sink.ready
		.rf_sink_valid           (cy7c67200_if_0_hpi_agent_rsp_fifo_out_valid),            //                .valid
		.rf_sink_startofpacket   (cy7c67200_if_0_hpi_agent_rsp_fifo_out_startofpacket),    //                .startofpacket
		.rf_sink_endofpacket     (cy7c67200_if_0_hpi_agent_rsp_fifo_out_endofpacket),      //                .endofpacket
		.rf_sink_data            (cy7c67200_if_0_hpi_agent_rsp_fifo_out_data),             //                .data
		.rf_source_ready         (cy7c67200_if_0_hpi_agent_rf_source_ready),               //       rf_source.ready
		.rf_source_valid         (cy7c67200_if_0_hpi_agent_rf_source_valid),               //                .valid
		.rf_source_startofpacket (cy7c67200_if_0_hpi_agent_rf_source_startofpacket),       //                .startofpacket
		.rf_source_endofpacket   (cy7c67200_if_0_hpi_agent_rf_source_endofpacket),         //                .endofpacket
		.rf_source_data          (cy7c67200_if_0_hpi_agent_rf_source_data),                //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_001_out_0_ready),                      // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_001_out_0_valid),                      //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_001_out_0_data),                       //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_001_out_0_error),                      //                .error
		.rdata_fifo_src_ready    (cy7c67200_if_0_hpi_agent_rdata_fifo_src_ready),          //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (cy7c67200_if_0_hpi_agent_rdata_fifo_src_valid),          //                .valid
		.rdata_fifo_src_data     (cy7c67200_if_0_hpi_agent_rdata_fifo_src_data),           //                .data
		.m0_response             (2'b00),                                                  //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                    //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (93),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) cy7c67200_if_0_hpi_agent_rsp_fifo (
		.clk               (pll_c2_clk),                                             //       clk.clk
		.reset             (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (cy7c67200_if_0_hpi_agent_rf_source_data),                //        in.data
		.in_valid          (cy7c67200_if_0_hpi_agent_rf_source_valid),               //          .valid
		.in_ready          (cy7c67200_if_0_hpi_agent_rf_source_ready),               //          .ready
		.in_startofpacket  (cy7c67200_if_0_hpi_agent_rf_source_startofpacket),       //          .startofpacket
		.in_endofpacket    (cy7c67200_if_0_hpi_agent_rf_source_endofpacket),         //          .endofpacket
		.out_data          (cy7c67200_if_0_hpi_agent_rsp_fifo_out_data),             //       out.data
		.out_valid         (cy7c67200_if_0_hpi_agent_rsp_fifo_out_valid),            //          .valid
		.out_ready         (cy7c67200_if_0_hpi_agent_rsp_fifo_out_ready),            //          .ready
		.out_startofpacket (cy7c67200_if_0_hpi_agent_rsp_fifo_out_startofpacket),    //          .startofpacket
		.out_endofpacket   (cy7c67200_if_0_hpi_agent_rsp_fifo_out_endofpacket),      //          .endofpacket
		.csr_address       (2'b00),                                                  // (terminated)
		.csr_read          (1'b0),                                                   // (terminated)
		.csr_write         (1'b0),                                                   // (terminated)
		.csr_readdata      (),                                                       // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                   // (terminated)
		.almost_full_data  (),                                                       // (terminated)
		.almost_empty_data (),                                                       // (terminated)
		.in_empty          (1'b0),                                                   // (terminated)
		.out_empty         (),                                                       // (terminated)
		.in_error          (1'b0),                                                   // (terminated)
		.out_error         (),                                                       // (terminated)
		.in_channel        (1'b0),                                                   // (terminated)
		.out_channel       ()                                                        // (terminated)
	);

	DE2_115_SOPC_mm_interconnect_1_router router (
		.sink_ready         (clock_crossing_io_m0_agent_cp_ready),                    //      sink.ready
		.sink_valid         (clock_crossing_io_m0_agent_cp_valid),                    //          .valid
		.sink_data          (clock_crossing_io_m0_agent_cp_data),                     //          .data
		.sink_startofpacket (clock_crossing_io_m0_agent_cp_startofpacket),            //          .startofpacket
		.sink_endofpacket   (clock_crossing_io_m0_agent_cp_endofpacket),              //          .endofpacket
		.clk                (pll_c2_clk),                                             //       clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                       //       src.ready
		.src_valid          (router_src_valid),                                       //          .valid
		.src_data           (router_src_data),                                        //          .data
		.src_channel        (router_src_channel),                                     //          .channel
		.src_startofpacket  (router_src_startofpacket),                               //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                  //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_router_001 router_001 (
		.sink_ready         (sysid_control_slave_agent_rp_ready),                     //      sink.ready
		.sink_valid         (sysid_control_slave_agent_rp_valid),                     //          .valid
		.sink_data          (sysid_control_slave_agent_rp_data),                      //          .data
		.sink_startofpacket (sysid_control_slave_agent_rp_startofpacket),             //          .startofpacket
		.sink_endofpacket   (sysid_control_slave_agent_rp_endofpacket),               //          .endofpacket
		.clk                (pll_c2_clk),                                             //       clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                   //       src.ready
		.src_valid          (router_001_src_valid),                                   //          .valid
		.src_data           (router_001_src_data),                                    //          .data
		.src_channel        (router_001_src_channel),                                 //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                           //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                              //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_router_001 router_002 (
		.sink_ready         (cy7c67200_if_0_hpi_agent_rp_ready),                      //      sink.ready
		.sink_valid         (cy7c67200_if_0_hpi_agent_rp_valid),                      //          .valid
		.sink_data          (cy7c67200_if_0_hpi_agent_rp_data),                       //          .data
		.sink_startofpacket (cy7c67200_if_0_hpi_agent_rp_startofpacket),              //          .startofpacket
		.sink_endofpacket   (cy7c67200_if_0_hpi_agent_rp_endofpacket),                //          .endofpacket
		.clk                (pll_c2_clk),                                             //       clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                                   //       src.ready
		.src_valid          (router_002_src_valid),                                   //          .valid
		.src_data           (router_002_src_data),                                    //          .data
		.src_channel        (router_002_src_channel),                                 //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                           //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                              //          .endofpacket
	);

	altera_merlin_traffic_limiter #(
		.PKT_DEST_ID_H             (78),
		.PKT_DEST_ID_L             (78),
		.PKT_SRC_ID_H              (77),
		.PKT_SRC_ID_L              (77),
		.PKT_BYTE_CNT_H            (66),
		.PKT_BYTE_CNT_L            (64),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_TRANS_POSTED          (59),
		.PKT_TRANS_WRITE           (60),
		.MAX_OUTSTANDING_RESPONSES (1),
		.PIPELINED                 (0),
		.ST_DATA_W                 (92),
		.ST_CHANNEL_W              (2),
		.VALID_WIDTH               (2),
		.ENFORCE_ORDER             (1),
		.PREVENT_HAZARDS           (0),
		.SUPPORTS_POSTED_WRITES    (1),
		.SUPPORTS_NONPOSTED_WRITES (0),
		.REORDER                   (0)
	) clock_crossing_io_m0_limiter (
		.clk                    (pll_c2_clk),                                             //       clk.clk
		.reset                  (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.cmd_sink_ready         (router_src_ready),                                       //  cmd_sink.ready
		.cmd_sink_valid         (router_src_valid),                                       //          .valid
		.cmd_sink_data          (router_src_data),                                        //          .data
		.cmd_sink_channel       (router_src_channel),                                     //          .channel
		.cmd_sink_startofpacket (router_src_startofpacket),                               //          .startofpacket
		.cmd_sink_endofpacket   (router_src_endofpacket),                                 //          .endofpacket
		.cmd_src_ready          (clock_crossing_io_m0_limiter_cmd_src_ready),             //   cmd_src.ready
		.cmd_src_data           (clock_crossing_io_m0_limiter_cmd_src_data),              //          .data
		.cmd_src_channel        (clock_crossing_io_m0_limiter_cmd_src_channel),           //          .channel
		.cmd_src_startofpacket  (clock_crossing_io_m0_limiter_cmd_src_startofpacket),     //          .startofpacket
		.cmd_src_endofpacket    (clock_crossing_io_m0_limiter_cmd_src_endofpacket),       //          .endofpacket
		.rsp_sink_ready         (rsp_mux_src_ready),                                      //  rsp_sink.ready
		.rsp_sink_valid         (rsp_mux_src_valid),                                      //          .valid
		.rsp_sink_channel       (rsp_mux_src_channel),                                    //          .channel
		.rsp_sink_data          (rsp_mux_src_data),                                       //          .data
		.rsp_sink_startofpacket (rsp_mux_src_startofpacket),                              //          .startofpacket
		.rsp_sink_endofpacket   (rsp_mux_src_endofpacket),                                //          .endofpacket
		.rsp_src_ready          (clock_crossing_io_m0_limiter_rsp_src_ready),             //   rsp_src.ready
		.rsp_src_valid          (clock_crossing_io_m0_limiter_rsp_src_valid),             //          .valid
		.rsp_src_data           (clock_crossing_io_m0_limiter_rsp_src_data),              //          .data
		.rsp_src_channel        (clock_crossing_io_m0_limiter_rsp_src_channel),           //          .channel
		.rsp_src_startofpacket  (clock_crossing_io_m0_limiter_rsp_src_startofpacket),     //          .startofpacket
		.rsp_src_endofpacket    (clock_crossing_io_m0_limiter_rsp_src_endofpacket),       //          .endofpacket
		.cmd_src_valid          (clock_crossing_io_m0_limiter_cmd_valid_data)             // cmd_valid.data
	);

	DE2_115_SOPC_mm_interconnect_1_cmd_demux cmd_demux (
		.clk                (pll_c2_clk),                                             //        clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), //  clk_reset.reset
		.sink_ready         (clock_crossing_io_m0_limiter_cmd_src_ready),             //       sink.ready
		.sink_channel       (clock_crossing_io_m0_limiter_cmd_src_channel),           //           .channel
		.sink_data          (clock_crossing_io_m0_limiter_cmd_src_data),              //           .data
		.sink_startofpacket (clock_crossing_io_m0_limiter_cmd_src_startofpacket),     //           .startofpacket
		.sink_endofpacket   (clock_crossing_io_m0_limiter_cmd_src_endofpacket),       //           .endofpacket
		.sink_valid         (clock_crossing_io_m0_limiter_cmd_valid_data),            // sink_valid.data
		.src0_ready         (cmd_demux_src0_ready),                                   //       src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                   //           .valid
		.src0_data          (cmd_demux_src0_data),                                    //           .data
		.src0_channel       (cmd_demux_src0_channel),                                 //           .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                           //           .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                             //           .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                                   //       src1.ready
		.src1_valid         (cmd_demux_src1_valid),                                   //           .valid
		.src1_data          (cmd_demux_src1_data),                                    //           .data
		.src1_channel       (cmd_demux_src1_channel),                                 //           .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),                           //           .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                              //           .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_cmd_mux cmd_mux (
		.clk                 (pll_c2_clk),                                             //       clk.clk
		.reset               (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                      //       src.ready
		.src_valid           (cmd_mux_src_valid),                                      //          .valid
		.src_data            (cmd_mux_src_data),                                       //          .data
		.src_channel         (cmd_mux_src_channel),                                    //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                              //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                   //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                   //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                 //          .channel
		.sink0_data          (cmd_demux_src0_data),                                    //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                           //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                              //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_cmd_mux cmd_mux_001 (
		.clk                 (pll_c2_clk),                                             //       clk.clk
		.reset               (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                                  //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                                  //          .valid
		.src_data            (cmd_mux_001_src_data),                                   //          .data
		.src_channel         (cmd_mux_001_src_channel),                                //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                          //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                            //          .endofpacket
		.sink0_ready         (cmd_demux_src1_ready),                                   //     sink0.ready
		.sink0_valid         (cmd_demux_src1_valid),                                   //          .valid
		.sink0_channel       (cmd_demux_src1_channel),                                 //          .channel
		.sink0_data          (cmd_demux_src1_data),                                    //          .data
		.sink0_startofpacket (cmd_demux_src1_startofpacket),                           //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src1_endofpacket)                              //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_rsp_demux rsp_demux (
		.clk                (pll_c2_clk),                                             //       clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                   //      sink.ready
		.sink_channel       (router_001_src_channel),                                 //          .channel
		.sink_data          (router_001_src_data),                                    //          .data
		.sink_startofpacket (router_001_src_startofpacket),                           //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                             //          .endofpacket
		.sink_valid         (router_001_src_valid),                                   //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                   //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                   //          .valid
		.src0_data          (rsp_demux_src0_data),                                    //          .data
		.src0_channel       (rsp_demux_src0_channel),                                 //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                           //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                              //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_rsp_demux rsp_demux_001 (
		.clk                (pll_c2_clk),                                             //       clk.clk
		.reset              (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                                   //      sink.ready
		.sink_channel       (router_002_src_channel),                                 //          .channel
		.sink_data          (router_002_src_data),                                    //          .data
		.sink_startofpacket (router_002_src_startofpacket),                           //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                             //          .endofpacket
		.sink_valid         (router_002_src_valid),                                   //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                               //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                               //          .valid
		.src0_data          (rsp_demux_001_src0_data),                                //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                             //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),                       //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                          //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_1_rsp_mux rsp_mux (
		.clk                 (pll_c2_clk),                                             //       clk.clk
		.reset               (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                      //       src.ready
		.src_valid           (rsp_mux_src_valid),                                      //          .valid
		.src_data            (rsp_mux_src_data),                                       //          .data
		.src_channel         (rsp_mux_src_channel),                                    //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                              //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                   //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                   //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                 //          .channel
		.sink0_data          (rsp_demux_src0_data),                                    //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                           //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                             //          .endofpacket
		.sink1_ready         (rsp_demux_001_src0_ready),                               //     sink1.ready
		.sink1_valid         (rsp_demux_001_src0_valid),                               //          .valid
		.sink1_channel       (rsp_demux_001_src0_channel),                             //          .channel
		.sink1_data          (rsp_demux_001_src0_data),                                //          .data
		.sink1_startofpacket (rsp_demux_001_src0_startofpacket),                       //          .startofpacket
		.sink1_endofpacket   (rsp_demux_001_src0_endofpacket)                          //          .endofpacket
	);

	DE2_115_SOPC_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pll_c2_clk),                                             // in_clk_0.clk
		.in_rst_0_reset (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (sysid_control_slave_agent_rdata_fifo_src_data),          //     in_0.data
		.in_0_valid     (sysid_control_slave_agent_rdata_fifo_src_valid),         //         .valid
		.in_0_ready     (sysid_control_slave_agent_rdata_fifo_src_ready),         //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                           //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                          //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                          //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                           //         .error
	);

	DE2_115_SOPC_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter_001 (
		.in_clk_0_clk   (pll_c2_clk),                                             // in_clk_0.clk
		.in_rst_0_reset (clock_crossing_io_m0_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (cy7c67200_if_0_hpi_agent_rdata_fifo_src_data),           //     in_0.data
		.in_0_valid     (cy7c67200_if_0_hpi_agent_rdata_fifo_src_valid),          //         .valid
		.in_0_ready     (cy7c67200_if_0_hpi_agent_rdata_fifo_src_ready),          //         .ready
		.out_0_data     (avalon_st_adapter_001_out_0_data),                       //    out_0.data
		.out_0_valid    (avalon_st_adapter_001_out_0_valid),                      //         .valid
		.out_0_ready    (avalon_st_adapter_001_out_0_ready),                      //         .ready
		.out_0_error    (avalon_st_adapter_001_out_0_error)                       //         .error
	);

endmodule
